name: Automated judger
on: [push]

jobs:
  execute:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check file existence
        run: test -f ./saas.sh
      - name: Run judger
        run: ./scripts/grade_boot.sh
      - name: Print server log
        if: always()
        run: echo "Server logs:" && cat ./server_output
      - name: Upload failed case
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: failed
          path: ./failed
      - name: Upload verdict
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: judge
          path: ./judge
